// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.jarvan.grpcdemo.grpc;

public interface MemberLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvan.grpcdemo.grpc.MemberLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
