// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberListSerbice.proto

package com.jarvan.grpcdemo.grpc;

public final class MemberListSerbice {
  private MemberListSerbice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvan_grpcdemo_grpc_MemberListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jarvan_grpcdemo_grpc_MemberListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvan_grpcdemo_grpc_MemberListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jarvan_grpcdemo_grpc_MemberListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027MemberListSerbice.proto\022\030com.jarvan.gr" +
      "pcdemo.grpc\032\014Member.proto\"3\n\021MemberListR" +
      "equest\022\014\n\004page\030\001 \001(\005\022\020\n\010per_page\030\002 \001(\005\"F" +
      "\n\022MemberListResponse\0220\n\006member\030\001 \003(\0132 .c" +
      "om.jarvan.grpcdemo.grpc.Member2}\n\021Member" +
      "ListService\022h\n\013member_list\022+.com.jarvan." +
      "grpcdemo.grpc.MemberListRequest\032,.com.ja" +
      "rvan.grpcdemo.grpc.MemberListResponseB\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemberOuterClass.getDescriptor(),
        });
    internal_static_com_jarvan_grpcdemo_grpc_MemberListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jarvan_grpcdemo_grpc_MemberListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jarvan_grpcdemo_grpc_MemberListRequest_descriptor,
        new String[] { "Page", "PerPage", });
    internal_static_com_jarvan_grpcdemo_grpc_MemberListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jarvan_grpcdemo_grpc_MemberListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jarvan_grpcdemo_grpc_MemberListResponse_descriptor,
        new String[] { "Member", });
    MemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
