// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.jarvan.grpcdemo.grpc;

public final class MemberLoginSerbice {
  private MemberLoginSerbice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jarvan_grpcdemo_grpc_MemberLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jarvan_grpcdemo_grpc_MemberLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030MemberLoginSerbice.proto\022\030com.jarvan.g" +
      "rpcdemo.grpc\032\014Member.proto\"F\n\022MemberLogi" +
      "nRequest\0220\n\006member\030\001 \001(\0132 .com.jarvan.gr" +
      "pcdemo.grpc.Member\"$\n\023MemberLoginRespons" +
      "e\022\r\n\005token\030\001 \001(\t2\201\001\n\022MemberLoginService\022" +
      "k\n\014member_login\022,.com.jarvan.grpcdemo.gr" +
      "pc.MemberLoginRequest\032-.com.jarvan.grpcd" +
      "emo.grpc.MemberLoginResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MemberOuterClass.getDescriptor(),
        });
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jarvan_grpcdemo_grpc_MemberLoginRequest_descriptor,
        new String[] { "Member", });
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jarvan_grpcdemo_grpc_MemberLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jarvan_grpcdemo_grpc_MemberLoginResponse_descriptor,
        new String[] { "Token", });
    MemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
