// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberListSerbice.proto

package com.jarvan.grpcdemo.grpc;

public interface MemberListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvan.grpcdemo.grpc.MemberListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  java.util.List<Member>
      getMemberList();
  /**
   * <code>repeated .com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  Member getMember(int index);
  /**
   * <code>repeated .com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  int getMemberCount();
  /**
   * <code>repeated .com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  java.util.List<? extends MemberOrBuilder>
      getMemberOrBuilderList();
  /**
   * <code>repeated .com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  MemberOrBuilder getMemberOrBuilder(
      int index);
}
