// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Member.proto

package com.jarvan.grpcdemo.grpc;

public interface MemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvan.grpcdemo.grpc.Member)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string info = 3;</code>
   */
  String getInfo();
  /**
   * <code>string info = 3;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
