// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.jarvan.grpcdemo.grpc;

public interface MemberLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvan.grpcdemo.grpc.MemberLoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  boolean hasMember();
  /**
   * <code>.com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  Member getMember();
  /**
   * <code>.com.jarvan.grpcdemo.grpc.Member member = 1;</code>
   */
  MemberOrBuilder getMemberOrBuilder();
}
