// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/Person.proto

package org.example.protobuf;

public interface PersonListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.PersonList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.Person person = 1;</code>
   */
  java.util.List<org.example.protobuf.Person> 
      getPersonList();
  /**
   * <code>repeated .org.example.Person person = 1;</code>
   */
  org.example.protobuf.Person getPerson(int index);
  /**
   * <code>repeated .org.example.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .org.example.Person person = 1;</code>
   */
  java.util.List<? extends org.example.protobuf.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .org.example.Person person = 1;</code>
   */
  org.example.protobuf.PersonOrBuilder getPersonOrBuilder(
      int index);
}
