// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package org.example.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .org.example.proto.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<Person.PhoneNumber>
      getPhonesList();
  /**
   * <code>repeated .org.example.proto.Person.PhoneNumber phones = 4;</code>
   */
  Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .org.example.proto.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .org.example.proto.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends Person.PhoneNumberOrBuilder>
      getPhonesOrBuilderList();
  /**
   * <code>repeated .org.example.proto.Person.PhoneNumber phones = 4;</code>
   */
  Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
