// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package org.example.proto;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_PersonList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_PersonList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_PersonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022\021org.example.proto\"\335\001\n\006Pe" +
      "rson\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030" +
      "\003 \001(\t\0225\n\006phones\030\004 \003(\0132%.org.example.prot" +
      "o.Person.PhoneNumber\032P\n\013PhoneNumber\022\016\n\006n" +
      "umber\030\001 \001(\t\0221\n\004type\030\002 \001(\0162#.org.example." +
      "proto.Person.PhoneType\"!\n\tPhoneType\022\n\n\006M" +
      "OBILE\020\000\022\010\n\004HOME\020\001\"7\n\nPersonList\022)\n\006perso" +
      "n\030\001 \003(\0132\031.org.example.proto.Person\"\"\n\016Pe" +
      "rsonResponse\022\020\n\010greeting\030\001 \001(\t2U\n\014HelloS" +
      "ervice\022E\n\005hello\022\031.org.example.proto.Pers" +
      "on\032!.org.example.proto.PersonResponseB\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_Person_descriptor,
        new String[] { "Name", "Id", "Email", "Phones", });
    internal_static_org_example_proto_Person_PhoneNumber_descriptor =
      internal_static_org_example_proto_Person_descriptor.getNestedTypes().get(0);
    internal_static_org_example_proto_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_Person_PhoneNumber_descriptor,
        new String[] { "Number", "Type", });
    internal_static_org_example_proto_PersonList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_proto_PersonList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_PersonList_descriptor,
        new String[] { "Person", });
    internal_static_org_example_proto_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_proto_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_PersonResponse_descriptor,
        new String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
