// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package org.example.proto;

public interface PersonListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.PersonList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.proto.Person person = 1;</code>
   */
  java.util.List<Person>
      getPersonList();
  /**
   * <code>repeated .org.example.proto.Person person = 1;</code>
   */
  Person getPerson(int index);
  /**
   * <code>repeated .org.example.proto.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .org.example.proto.Person person = 1;</code>
   */
  java.util.List<? extends PersonOrBuilder>
      getPersonOrBuilderList();
  /**
   * <code>repeated .org.example.proto.Person person = 1;</code>
   */
  PersonOrBuilder getPersonOrBuilder(
      int index);
}
