// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package org.example.proto;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
